### ISSUE TITLE
친구리스트 클릭시 내브바 전체에 스크롤바 생기는 버그

### ISSUE THREAD

**Issue by DomMorello** [AMATEURTOSS/ft_transcendence#142]
![캡처](https://user-images.githubusercontent.com/51396282/132977812-3de5b202-8b9e-465c-81ed-efda35ab30f6.PNG)

**Comment by AMATEURTOSS** [comment]
생각해 봤는데, 가로 길이에 대한 media 를 적용시키기 보다는 스크롤 허용시키는게 나은 것 같습니다.
세로 길이가 엄청 짧은 디스플레이를 사용하는 유저가 있을 수도 있으니까요
