### ISSUE TITLE
NavBar anchor의 padding이 navbar 보다 작음

### ISSUE THREAD

**Issue by AMATEURTOSS** [AMATEURTOSS/ft_transcendence#16]
<img width="280" alt="스크린샷 2021-07-08 오후 3 16 13" src="https://user-images.githubusercontent.com/50163242/124871931-a1415500-dfff-11eb-8e59-1f7c2c174f0c.png">

앵커의 height 는 53px, navbar의 height는 56 임

**Comment by DomMorello** [comment]
이 이슈는 해결된건가요? 지금 확인해보니까 a 높이 55.6나오고 NavBar 높이는 56 나오는데 수정 필요없을것 같습니다.
문제가 될만한게 있을까요?

**Comment by AMATEURTOSS** [comment]
아직 딱히 수정사항 없는데... 마스터 브랜치에서 확인해보시면 a height 53 나올걸요??

**Comment by DomMorello** [comment]
마스터브랜치로 55.6 나오는데;; 컴퓨터마다 다른건가 ㅎㅎㅎ
