### ISSUE TITLE
img source 를 로컬 이미지로 바꾸기

### ISSUE THREAD

**Issue by AMATEURTOSS** [AMATEURTOSS/ft_transcendence#27]
현재 NavBar의 icon들을 (e.g.  icon-record) 다른 웹서버에서 가져오는 방식으로 사용하고 있는데,
시간 날 때 이 이미지들을 다운로드 받아서 public 디렉토리에 넣어서 활용했으면 좋겠습니다.
왜 Why: 이미지를 가져오는 호스트 server가 다운되면 우리 측에서 대응할 수 없습니다.
우리가 제어할 수 있는 수단을 사용해야 한다고 생각합니다.

p.s. doge 이미지 (현재 navbar 최상단에 있는 이미지)는 테스트용 이미지이므로 바꾸지 않아도 됩니다.

**Comment by DomMorello** [comment]
아주 좋은 지적이네요 차후에 수정하고 앞으로도 지적해주신 방법으로 진행하겠습니다!
