### ISSUE TITLE
Login process 개선

### ISSUE THREAD

**Issue by AMATEURTOSS** [AMATEURTOSS/ft_transcendence#28]
현재 `/` 와 `/mainpage` 로 주소가 나뉘어 있는데, 이걸 `/` 주소 하나로 통합하려고 합니다.

애초에 나눴던 이유가 backend 에서 sid, token 의 유효성을 검사해줄 수단이 없었기 때문인데
backend에서 유효성 검사 api가 완성되면 그럴 필요가 없을 것 같습니다.

flow 는 다음과 같습니다.

![login_flow](https://user-images.githubusercontent.com/50163242/125283728-a67e0700-e353-11eb-8138-5eb4d8d80e80.png)

**Comment by DomMorello** [comment]
백엔드 코드도 좀 봐야 원리가 이해갈 것 같네요ㅠ
