### ISSUE TITLE
chat 초대하기 검색 버그

### ISSUE THREAD

**Issue by AMATEURTOSS** [AMATEURTOSS/ft_transcendence#306]
## 버그 내용
검색  input을 비워놓은 상태로 검색 버튼을 누르면 아래와 같이 됨
## 버그 스샷
<img width="1439" alt="스크린샷 2021-11-02 오후 2 41 07" src="https://user-images.githubusercontent.com/50163242/139792533-3ef8bcce-d2ad-4660-bb50-5f8675c7101d.png">

**Comment by DomMorello** [comment]
확인했습니다. 예외처리할게요
