### ISSUE TITLE
전적 디자인 변경

### ISSUE THREAD

**Issue by AMATEURTOSS** [AMATEURTOSS/ft_transcendence#59]
1. 전적 검색 placeholder 닉네임 -> 전적 검색할 닉네임 등 좀 더 친절하게 변경
2. 전적 검색 버튼 search -> 돋보기 모양으로 변경

**Comment by DomMorello** [comment]
3. 전적 리스트에 나오는 부분 동그란 아바타모양이 조금 더 작았으면 좋겠습니다. 지금 너무 그 가로로 있는 바 안에 가득 차있는 느낌이라서 조금 padding이 있으면 이쁠 것 같습니다.
4. 리스트 우측에 15분전 general map1 이것도 한글로 바꿔주시고 이것도 마찬가지로 조금 작게해서 padding이 조금 있으면 좋겠습니다!
