### ISSUE TITLE
/chat response 에서 private 채팅방이 보임

### ISSUE THREAD

**Issue by AMATEURTOSS** [AMATEURTOSS/ft_transcendence#63]
private 채팅방이 응답에 들어있으면 사용자가 Chrome Network탭에서 비밀 채팅방까지 확인할 수 있습니다.
private 채팅방 취지에 맞지 않는 것 같아서 private 채팅방은 빼놓고 응답하는 등 개선이 필요해 보입니다.

<img width="510" alt="스크린샷 2021-08-08 오후 4 44 01" src="https://user-images.githubusercontent.com/50163242/128624835-67f8fc6a-45a7-4815-a8b4-bd3d33fa7039.png">

**Comment by jinbkim** [comment]
넵 채널검색할때 private 채팅방은 제외하고 응답하도록 변경하겠습니다~
